StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6529112CBD590F73}" {
   Id "DRG-Role-AntiTank"
   Target_en_us "Rifleman AT"
   Target_ru_ru "Гранатомётчик"
   Modified 1697207597
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6529112C755F13A2}" {
   Id "DRG-Role-AssistantAT"
   Target_en_us "Assistant Anti-Tank"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1697190820
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E1DBBC868D}" {
   Id "DRG-Role-Driver"
   Target_en_us "Driver"
   Target_ru_ru "Водитель"
   Modified 1683827129
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E224CBF818}" {
   Id "DRG-Role-Engineer"
   Target_en_us "Engineer"
   Target_ru_ru "Инженер"
   Modified 1683828368
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D6E60496F5ECAB}" {
   Id "DRG-Role-LeaderRebel"
   Target_en_us "Rebel TeamLeader"
   Target_ru_ru "Командир группы ополчения"
   Modified 1691812563
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D6E6063F14BF63}" {
   Id "DRG-Role-Milita"
   Target_en_us "Rebel"
   Target_ru_ru "Ополченец"
   Modified 1691811174
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E0A9C7C030}" {
   Id "DRG-Role-Mortar-TL"
   Target_en_us "Mortar Crew Commander"
   Target_ru_ru "Командир миномётного расчёта"
   Modified 1697205883
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64CE753FE04B854D}" {
   Id "DRG-Role-MortarAmmoBearer"
   Target_en_us "Mortar Ammo Bearer"
   Target_ru_ru "Подносчик миномётного расчёта"
   Modified 1697205892
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E36B461D5A}" {
   Id "DRG-Role-MortarGunner"
   Target_en_us "Mortar Gunner"
   Target_ru_ru "Наводчик миномёта"
   Modified 1697205897
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E348803A0C}" {
   Id "DRG-Role-MortarLoader"
   Target_en_us "Mortar Loader"
   Target_ru_ru "Заряжающий миномёта"
   Modified 1697205901
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{65113370643057FD}" {
   Id "DRG-Role-MortarSpotter"
   Target_en_us "Mortar Spotter"
   Target_ru_ru "Арт.коррективщик"
   Modified 1695628533
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64D6E606FA027633}" {
   Id "DRG-Role-Rebel"
   Target_en_us "Rebel"
   Target_ru_ru "Ополченец"
   Modified 1691812308
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64F8ACC0FDF4F7E8}" {
   Id "Drg-Role-SeniorEngineer"
   Target_en_us "Senior Engineer"
   Target_ru_ru "Старший инженер"
   Modified 1694019164
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543EF74F189EC}" {
   Id "DRG-Role_AntiTank"
   Target_en_us "Anti-Tank Specialist"
   Target_ru_ru "Гранатомётчик"
   Modified 1639283730
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D20F4503DA}" {
   Id "DRG-Role_AntiTankAssistant"
   Target_en_us "Anti-Tank Assistant"
   Target_ru_ru "Помощник гранатомётчика"
   Modified 1639317917
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FC7BD30748}" {
   Id "DRG-Role_CompanyLeader"
   Target_en_us "Company Leader"
   Target_ru_ru "Командир роты"
   Modified 1683829399
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6529112BC5E5937A}" {
   Id "DRG-Role_CrewCommanderV"
   Target_en_us "Crew Commander"
   Target_ru_ru "Командир экипажа"
   Modified 1697193366
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D639D70EE4}" {
   Id "DRG-Role_CrewDriver"
   Target_en_us "Crew Driver"
   Target_ru_ru "Механик-водитель"
   Modified 1639319711
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D66CC845E4}" {
   Id "DRG-Role_CrewGunner"
   Target_en_us "Crew Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1697193476
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D551D4FF581}" {
   Id "DRG-Role_EngineerSapper"
   Target_en_us "Engineer Sapper"
   Target_ru_ru "Инженер сапёр"
   Modified 1639346789
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E6723A25C4}" {
   Id "DRG-Role_EngineerSeniorSapper"
   Target_en_us "Senior Engineer Sapper"
   Target_ru_ru "Старший инженер сапёр"
   Modified 1683826417
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D7D6CFDE6C}" {
   Id "DRG-Role_Recon"
   Target_en_us "Scout"
   Target_ru_ru "Разведчик"
   Modified 1639352849
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D47D30DA77D}" {
   Id "DRG-Role_Recon_Medic"
   Target_en_us "Scout Medic"
   Target_ru_ru "Разведчик-санитар"
   Modified 1639353787
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A51EA1FA9D35}" {
   Id "DRG-Role_Recon_Officer"
   Target_en_us "Scount Officer"
   Target_ru_ru "Офицер разведки"
   Modified 1639495009
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D59F2619D28}" {
   Id "DRG-Role_Recon_PL"
   Target_en_us "Scout Platoon Leader"
   Target_ru_ru "Командир развед.взвода"
   Modified 1639352821
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5ADE31F74D}" {
   Id "DRG-Role_ReconAR"
   Target_en_us "Scout Automatic Rifleman"
   Target_ru_ru "Разведчик-пулемётчик"
   Modified 1639352433
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D596818E85B}" {
   Id "DRG-Role_ReconAT"
   Target_en_us "Scount Aniti-Tank Specialist"
   Target_ru_ru "Разведчик-гранатомётчик"
   Modified 1639352577
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B8A5135CBA7D37}" {
   Id "DRG-Role_ReconBearer"
   Target_en_us "Scout Ammo Bearer"
   Target_ru_ru "Разведчик-подносчик"
   Modified 1639493995
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B543D44D597D0A}" {
   Id "DRG-Role_ReconRifleman"
   Target_en_us "Scount Rifleman"
   Target_ru_ru "Разведчик-стрелок"
   Modified 1639347238
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5A52FF55AA}" {
   Id "DRG-Role_ReconRTO"
   Target_en_us "Scout RTO"
   Target_ru_ru "Разведчик-радиотелефонист"
   Modified 1639352186
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D54696A9850}" {
   Id "DRG-Role_ReconSapper"
   Target_en_us "Scount Sapper"
   Target_ru_ru "Разведчик-сапёр"
   Modified 1639347280
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B613230BF7A35A}" {
   Id "DRG-Role_ReconSeniorScount"
   Target_en_us "Senior Scount"
   Target_ru_ru "Старший разведчик"
   Modified 1639322535
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D5B5682B098}" {
   Id "DRG-Role_ReconSL"
   Target_en_us "Scout Leader"
   Target_ru_ru "Командир развед.группы"
   Modified 1639351733
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61B66D54C3A5D447}" {
   Id "DRG-Role_ReconSniper"
   Target_en_us "Scount Sniper"
   Target_ru_ru "Разведчик-снайпер"
   Modified 1639347871
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6170D2157DE458A0}" {
   Id "DRG-Role_Watchman"
   Target_en_us "Old watchman"
   Target_ru_ru "Старый сторож"
   Modified 1639283579
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E75DF0E96F}" {
   Id "DRG-Sq-Battalion_HQ"
   Target_en_us "Battalion command"
   Target_ru_ru "Упр. батальона"
   Modified 1683825973
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FDB8B305FF}" {
   Id "DRG-Sq-CompanyHQ"
   Target_en_us "Company Headquarters"
   Target_ru_ru "Управление роты"
   Modified 1683829323
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E260BAB97E}" {
   Id "DRG-Sq-EngineeringDetachment"
   Target_en_us "Repair detachment"
   Target_ru_ru "Ремонтное-отд."
   Modified 1683829075
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F6DB50E586}" {
   Id "DRG-Sq-HeliGunTransport"
   Target_en_us "Helicopter (MG)"
   Target_ru_ru "Вооруженный вертолёт"
   Modified 1683834869
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F6216E0035}" {
   Id "DRG-Sq-HeliTransport"
   Target_en_us "Transport crew"
   Target_ru_ru "Транспортный вертолёт"
   Modified 1683834844
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FC990D7C47}" {
   Id "DRG-Sq-MachineGunnerSquad"
   Target_en_us "Machine gunner squad"
   Target_ru_ru "Пулемётное отделение"
   Modified 1683829801
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FDFD85EC84}" {
   Id "DRG-Sq-MedicalTeam"
   Target_en_us "Medic team"
   Target_ru_ru "Медицинское отделение"
   Modified 1683829162
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E0F71BE16C}" {
   Id "DRG-Sq-MortarCrew"
   Target_en_us "Mortar Crew"
   Target_ru_ru "Миномётный расчёт"
   Modified 1697205906
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FEB27235E3}" {
   Id "DRG-Sq-PlatoonHQ"
   Target_en_us "Platoon Headquarters"
   Target_ru_ru "Управление взвода"
   Modified 1683830682
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64F127C553117A4D}" {
   Id "DRG-Sq-Rebels"
   Target_en_us "Rebel squad"
   Target_ru_ru "Отряд партизан"
   Modified 1693543266
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{64CE7531F3425609}" {
   Id "DRG-Sq-ReconCompanyHQ"
   Target_en_us "Recon Company HQ"
   Target_ru_ru "Управление развед.роты"
   Modified 1691254125
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F5F35E47AF}" {
   Id "DRG-Sq-ReconPlatoonHQ"
   Target_en_us "Recon Platoon HQ"
   Target_ru_ru "Управление развед.взвода"
   Modified 1683833674
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F7C8444980}" {
   Id "DRG-Sq-ReconSquad"
   Target_en_us "Recon Squad"
   Target_ru_ru "Развед.отделение"
   Modified 1683834096
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4FA36B5C7A3}" {
   Id "DRG-Sq-RifleSquad"
   Target_en_us "Rifle squad"
   Target_ru_ru "Стрелковое отделение"
   Modified 1683832267
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4F699DC84C2}" {
   Id "DRG-Sq-RocketHelicopter"
   Target_en_us "Helicopter (Rocket)"
   Target_ru_ru "Ударно-траспортный верт."
   Modified 1683834908
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E6C4179AF9}" {
   Id "DRG-Sq-SupplyTeam"
   Target_en_us "Supply team"
   Target_ru_ru "Группа снабжения"
   Modified 1683826725
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{645CD4E7DA63D84A}" {
   Id "DRG-Sq_DemolitionTeam"
   Target_en_us "Demolition team"
   Target_ru_ru "Сапёрное звено"
   Modified 1683826225
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CB0A080F880E4D}" {
   Id "DRG-Weapon_NSP_Description"
   Target_en_us "Ground signal cartridge NSP, orange smoke. Used by the Soviet Army to send signals. Most often to indicate their positions in the event of friendly fire."
   Target_ru_ru "Наземный сигнальный патрон НСП, оранжевый дым. Используется Советсткой Армии для подачи сигналов. Чаще всего для обозначения своих позиций в случае дружественного огня."
   Modified 1640696647
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{61CB0A082F65E9E8}" {
   Id "DRG-Weapon_NSP_Name"
   Target_en_us "NSP"
   Target_ru_ru "НСП"
   Modified 1640696536
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{62BED26AD2D8D92B}" {
   Id "DRG_ChangeFlagAction"
   Target_en_us "Change flag"
   Target_ru_ru "Поменять флаг"
   Modified 1656675458
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6483160DA279A5F6}" {
   Id "DRG_DeputyPL"
   Target_en_us "Deputy platoon leader"
   Target_ru_ru "Зам. командира взвода"
   Modified 1686317388
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{651B0835C9CB5A9D}" {
   Id "DRG_FlagChangeForbidden"
   Target_en_us "Change forbidden"
   Target_ru_ru "Смена флага запрещена"
   Modified 1696273832
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{651B0835E5136035}" {
   Id "DRG_ItsYourFlag"
   Target_en_us "Its your flag"
   Target_ru_ru "Это ваш флаг"
   Modified 1696273764
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6328C0238BB9D206}" {
   Id "DRG_Role_TV"
   Target_en_us "Yuri Vladimirovich (TV presenter)"
   Target_ru_ru "Юрий Владимирович (Телеведущий)"
   Modified 1663630906
   Author "hasta"
   LastChanged "hasta"
  }
  CustomStringTableItem "{6525161AC5EB16FB}" {
   Id "DRG_Scripts_CriticalLossTitle"
   Target_en_us "Критические потери"
   Target_ru_ru "Критические потери"
   Modified 1696931101
   Author "hasta"
   LastChanged "hasta"
  }
 }
}